### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by Nyholm** [php-http/discovery#103]
Last release was in August. We have a few minor commits in master that is not released yet. What do you think of releasing 1.4.0 this year?

**Comment by dbu** [comment]
i honestly don't see any value in releasing, as nothing much changed. using ::class constants seems to be the only change and that is purely a code style thing imho. or is there value in bringing that to the users? is that enough to need a new minor version or could we tag 1.3.1?

**Comment by joelwurtz** [comment]
We could add https://github.com/Nyholm/psr7 to the message factory discovery (and i would actually make it top 1 in the list since it's the only one that is 100% compatible with PSR7)

And also Artax as an async adapter once the PR has been merged and then release a new version ?

**Comment by tuupola** [comment]
I am big fan of `nyholm/psr7` so +1 for adding it.

**Comment by dbu** [comment]
if we have any valuable things to add, i agree we should do that and then release.

**Comment by NickvdMeij** [comment]
@Nyholm see https://github.com/php-http/discovery/issues/105. This change currently breaks all Magento 2 installations that use mailgun/mailgun-php, resulting in emails not being sent.

**Comment by Nyholm** [comment]
Closing this since 1.4 has been released
