### ISSUE TITLE
Release 1.6.0

### ISSUE THREAD

**Issue by Nyholm** [php-http/discovery#134]
Should we have a plan?

**Comment by dbu** [comment]
are there any unreleased changes that we need to release?

**Comment by Nyholm** [comment]
Yeah, The PSR17 and PSR18 features

**Comment by dbu** [comment]
ah right, the release page is somehow confused and only shows the diff link on version 1.5.0, but not 1.5.1 or 1.5.2. the diff is https://github.com/php-http/discovery/compare/1.5.2...master

i guess we are ready to release it, or anything we need to do? documentation seems to be missing: http://docs.php-http.org/en/latest/discovery.html

**Comment by Nyholm** [comment]
Added docs here: https://github.com/php-http/documentation/pull/249
