### ISSUE TITLE
Support the Symfony PSR-18 http client ?

### ISSUE THREAD

**Issue by Taluu** [php-http/discovery#138]
| Q            | A
| ------------ | ---
| Bug?         | no
| New Feature? | yes
| Version      | master ?

#### Actual Behavior
The discovery doesn't discover the symfony http client, especially its psr-18 bridge. Would be great to support that IMO.

#### Expected Behavior
Being able to discover the PSR-18 adapter of the brand new Symfony HttpClient component.

I'll try a PR once the component is merged and released (or maybe before ?)

**Comment by dbu** [comment]
sure, go ahead. we will not merge anything before the symfony component is released, but trying it out now is a good idea, to discover potential problems before it is released.

**Comment by Taluu** [comment]
As this was implemented, I guess this can be now closed. Unless you'd like to keep this open until there's a release ? Feel free to reopen if that's the case.
