### ISSUE TITLE
Fix interface hack in tests

### ISSUE THREAD

**Issue by dbu** [php-http/discovery#14]
we should enable travis for this repository and fix the phpspec tests. HttpClientDiscoverySpec still uses Http\Adapter\HttpAdapter which can't be right. there is not even a dependency on php-http/httplug. we might also want some functional tests that instantiate an actual client.

**Comment by sagikazarmark** [comment]
As I can see Travis is enabled.

**Comment by dbu** [comment]
hm. but then i have some doubts about either phpspec or how we wrote the
tests. Http\Adapter\HttpAdapter is not existing anymore. and there are
no implementations in the composer.json so the find() would need to mock
something.

ah, ok, the bootstrap.php is creating weird fixtures. i would prefer not
to mock that to avoid such confusion. if we want to keep mocking, we
should mock the correct naming to make it less confusing :-)

**Comment by sagikazarmark** [comment]
Not sure why I originally did this, but there was some reason. I guess to avoid insane Guzzle dependencies, because Guzzle adapters were not stable at that time. Also, guzzle 5 and 6 are conflicting with each other. I would just fix the fixtures and deal with it later, when we have stable packages.

**Comment by dbu** [comment]
okay. can you do that?

**Comment by sagikazarmark** [comment]
Already did. :wink:

**Comment by sagikazarmark** [comment]
Leaving this open in order to make sure it eventually gets solved.

**Comment by dbu** [comment]
is this still relevant? or did we fix that?
