### ISSUE TITLE
Release 1.7.0 ?

### ISSUE THREAD

**Issue by Taluu** [php-http/discovery#142]
| Q            | A
| ------------ | ---
| Bug?         | no
| New Feature? | no ?
| Version      | e444002

As this package has been updated with the support of the new Symfony Http Client and priorities being reset for the Buzz client, shouldn't we release a new version ? Even though the changelog may be a bit skinny.

#### Possible Solutions
Release 1.7.0 ? :}

**Comment by Nyholm** [comment]
Excellent idea. I just added the changelog #143
