### ISSUE TITLE
PSR-18 client discovery will not find the Mock client

### ISSUE THREAD

**Issue by pascalwoerde** [php-http/discovery#144]
| Q            | A
| ------------ | ---
| Bug?         |yes
| New Feature? | no

#### Actual Behavior

A DiscoveryFailedException is thrown.

#### Expected Behavior

An instance of the mock client.

#### Steps to Reproduce

Using the Psr18ClientDiscovery will result in a DiscoveryFailedException (MockClientStrategy is prepended) since the current MockClientStrategy have no candidate for the PSR ClientInterface.

#### Possible Solutions

Will open a PR soon.

**Comment by dbu** [comment]
this is on purpose. we do not want discovery to make an application accidentally use the mock client. the mock client is only for testing.

**Comment by dbu** [comment]
oh, seems we already changed this and discovery now finds mock but is broken. thanks for the pull request.

**Comment by xabbuh** [comment]
Is this something that we need to consider in the other strategies too?
