### ISSUE TITLE
No HTTPlug clients found

### ISSUE THREAD

**Issue by rfussien** [php-http/discovery#155]
| Q            | A
| ------------ | ---
| Bug?         | yes
| New Feature? | no
| Version      | 1.7.1

#### Actual Behavior

I'm using the thephpleague/omnipay package and since the release of the version 1.7.1, HttpClientDiscovery is not able to find the http client I'm using (_symfony/http-client_) any more.

  +"message": "No HTTPlug clients found. Make sure to install a package providing "php-http/client-implementation". Example: "php-http/guzzle6-adapter"."
  +"exception": "Http\Discovery\NotFoundException"

#### Expected Behavior

I would expect discovery to find symfony http client.

**Comment by dbu** [comment]
does it work again with 1.7.2? if not, can you confirm that it works with 1.7.0? if that does, do you have an idea what of https://github.com/php-http/discovery/compare/1.7.0...master could be the cause?

**Comment by rfussien** [comment]
Yes I Confirme it works with 1.7.0 and 1.7.2 and not 1.7.1.
Thank you for the quick fix ;)

**Comment by dbu** [comment]
the fix was @Nyholm 's ;-)
