### ISSUE TITLE
[Symfony 4.4] No PSR-17 response factory found

### ISSUE THREAD

**Issue by XWB** [php-http/discovery#156]
It seems https://github.com/php-http/discovery/issues/149 is still not fixed. The fix that was proposed in https://github.com/php-http/discovery/pull/150 was reverted in https://github.com/php-http/discovery/pull/151

> No PSR-17 response factory found. Install a package from this list: https://packagist.org/providers/psr/http-factory-implementation

>  Could not find resource using any discovery strategy. Find more information at http://docs.php-http.org/en/latest/discovery.html#common-errors
>  - Puli Factory is not available
>  - No valid candidate found using strategy "Http\Discovery\Strategy\CommonClassesStrategy". We tested the following candidates: .
>  - No valid candidate found using strategy "Http\Discovery\Strategy\CommonPsr17ClassesStrategy". We tested the following candidates: Nyholm\Psr7\Factory\Psr17Factory, Zend\Diactoros\ResponseFactory, Http\Factory\Diactoros\ResponseFa
  ctory, Http\Factory\Guzzle\ResponseFactory, Http\Factory\Slim\ResponseFactory.

**Comment by Nyholm** [comment]
Oh. Both #150 and #151 are correct... 

We need the check for both interfaces... 

The HTTPlug message factory is needed becuase of this requirement 
https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/HttpClient/HttplugClient.php#L42-L48

And the PSR17 request factory is needed for the constructor argument.

**Comment by Nyholm** [comment]
Could you make a PR to update that?

(Also write a line in the changelog.md).

**Comment by dbu** [comment]
hopefully really fixed in 1.7.3 now
