### ISSUE TITLE
ClassDiscovery::safeClassExists broken

### ISSUE THREAD

**Issue by XWB** [php-http/discovery#158]
Version 1.7.2

It seems https://github.com/php-http/discovery/pull/154 broke something, because I now got the following error:

> No PSR-17 response factory found. Install a package from this list: https://packagist.org/providers/psr/http-factory-implementation

> Could not find resource using any discovery strategy. Find more information at http://docs.php-http.org/en/latest/discovery.html#common-errors - Puli Factory is not available - No valid candidate found using strategy "Http\Discovery\Strategy\CommonClassesStrategy". We tested the following candidates: . - No valid candidate found using strategy "Http\Discovery\Strategy\CommonPsr17ClassesStrategy". We tested the following candidates: Nyholm\Psr7\Factory\Psr17Factory, Zend\Diactoros\ResponseFactory, Http\Factory\Diactoros\ResponseFactory, Http\Factory\Guzzle\ResponseFactory, Http\Factory\Slim\ResponseFactory.

So when I revert this:

```php
    public static function safeClassExists($class)
    {
        try {
            return class_exists($class) || interface_exists($class);
        } catch (\Exception $e) {
            return false;
        }
```

Back to the old behavior:

```php
    public static function safeClassExists($class)
    {
        try {
            return class_exists($class);
        } catch (\Exception $e) {
            return false;
        }
```

Now the error is gone.

The debug trace points to https://github.com/FriendsOfSymfony/FOSHttpCache/blob/master/src/ProxyClient/HttpDispatcher.php#L99

Any idea what this could be?

**Comment by onEXHovia** [comment]
I Confirm the problem on the Version 1.7.3. After install `symfony/http-client` i get the same exception as @XWB.

<img width="1056" alt="Screenshot at Jan 02 21-24-12" src="https://user-images.githubusercontent.com/3332033/71678139-41347780-2da6-11ea-8c0e-c189111393ef.png">

**Comment by XWB** [comment]
Fixed in https://github.com/php-http/discovery/releases/tag/1.7.4
