### ISSUE TITLE
Symfony HttplugClient not found

### ISSUE THREAD

**Issue by garak** [php-http/discovery#165]
**PHP version**: 7.2.24

**Description**
I'm getting the infamous error, even with `symfony/http-client` installed:

>Could not find resource using any discovery strategy. Find more information at http://docs.php-http.org/en/latest/discovery.html#common-errors          
>- Puli Factory is not available                                             
>- No valid candidate found using strategy "Http\Discovery\Strategy\CommonClassesStrategy". We tested the following candidates: Symfony\Component\HttpClient\HttplugClient, Http\Adapter\Guzzle6\Client, Http\Client\Curl\Client, Http\Adapter\React\Client.                                                  
>- No valid candidate found using strategy "Http\Discovery\Strategy\CommonPsr17ClassesStrategy". We tested the following candidates: . 

**How to reproduce**
Sadly, I've no idea :cry: 

**Possible Solution**
same as above

**Additional context**

output of `composer show | egrep "symfony|php-http"`:

```
php-http/client-common             2.1.0              Common HTTP Client implementations and tools for HTTPlug
php-http/discovery                 1.7.4              Finds installed HTTPlug implementations and PSR-7 message factories
php-http/httplug                   2.1.0              HTTPlug, the HTTP client abstraction for PHP
php-http/message                   1.8.0              HTTP Message related tools
php-http/message-factory           v1.0.2             Factory interfaces for PSR-7 HTTP Message
php-http/promise                   v1.0.0             Promise used for asynchronous HTTP requests
sentry/sentry-symfony              3.3.1              Symfony integration for Sentry (http://getsentry.com)
symfony/asset                      v5.0.2             Symfony Asset Component
symfony/browser-kit                v5.0.2             Symfony BrowserKit Component
symfony/cache                      v5.0.2             Symfony Cache component with PSR-6, PSR-16, and tags
symfony/cache-contracts            v2.0.1             Generic abstractions related to caching
symfony/config                     v5.0.2             Symfony Config Component
symfony/console                    v5.0.2             Symfony Console Component
symfony/css-selector               v5.0.2             Symfony CssSelector Component
symfony/debug-bundle               v5.0.2             Symfony DebugBundle
symfony/dependency-injection       v5.0.2             Symfony DependencyInjection Component
symfony/doctrine-bridge            v5.0.2             Symfony Doctrine Bridge
symfony/dom-crawler                v5.0.2             Symfony DomCrawler Component
symfony/error-handler              v5.0.2             Symfony ErrorHandler Component
symfony/event-dispatcher           v5.0.2             Symfony EventDispatcher Component
symfony/event-dispatcher-contracts v2.0.1             Generic abstractions related to dispatching event
symfony/filesystem                 v5.0.2             Symfony Filesystem Component
symfony/finder                     v5.0.2             Symfony Finder Component
symfony/flex                       v1.6.0             Composer plugin for Symfony
symfony/form                       v5.0.2             Symfony Form Component
symfony/framework-bundle           v5.0.2             Symfony FrameworkBundle
symfony/http-client                v5.0.2             Symfony HttpClient component
symfony/http-client-contracts      v2.0.1             Generic abstractions related to HTTP clients
symfony/http-foundation            v5.0.2             Symfony HttpFoundation Component
symfony/http-kernel                v5.0.2             Symfony HttpKernel Component
symfony/inflector                  v5.0.2             Symfony Inflector Component
symfony/intl                       v5.0.2             A PHP replacement layer for the C intl extension that includes additional data from the ICU library.
symfony/messenger                  v5.0.2             Symfony Messenger Component
symfony/mime                       v5.0.2             A library to manipulate MIME messages
symfony/monolog-bridge             v5.0.2             Symfony Monolog Bridge
symfony/monolog-bundle             v3.5.0             Symfony MonologBundle
symfony/options-resolver           v5.0.2             Symfony OptionsResolver Component
symfony/phpunit-bridge             v5.0.2             Symfony PHPUnit Bridge
symfony/polyfill-php73             v1.13.1            Symfony polyfill backporting some PHP 7.3+ features to lower PHP versions
symfony/polyfill-uuid              v1.13.1            Symfony polyfill for uuid functions
symfony/process                    v5.0.2             Symfony Process Component
symfony/profiler-pack              v1.0.4             A pack for the Symfony web profiler
symfony/property-access            v5.0.2             Symfony PropertyAccess Component
symfony/routing                    v5.0.2             Symfony Routing Component
symfony/security-bundle            v5.0.2             Symfony SecurityBundle
symfony/security-core              v5.0.2             Symfony Security Component - Core Library
symfony/security-csrf              v5.0.2             Symfony Security Component - CSRF Library
symfony/security-guard             v5.0.2             Symfony Security Component - Guard
symfony/security-http              v5.0.2             Symfony Security Component - HTTP Integration
symfony/service-contracts          v2.0.1             Generic abstractions related to writing services
symfony/stopwatch                  v5.0.2             Symfony Stopwatch Component
symfony/string                     v5.0.2             Symfony String component
symfony/swiftmailer-bundle         v3.4.0             Symfony SwiftmailerBundle
symfony/translation                v5.0.2             Symfony Translation Component
symfony/translation-contracts      v2.0.1             Generic abstractions related to translation
symfony/twig-bridge                v5.0.2             Symfony Twig Bridge
symfony/twig-bundle                v5.0.2             Symfony TwigBundle
symfony/validator                  v5.0.2             Symfony Validator Component
symfony/var-dumper                 v5.0.2             Symfony mechanism for exploring and dumping PHP variables
symfony/var-exporter               v5.0.2             A blend of var_export() + serialize() to turn any serializable data structure to plain PHP code
symfony/web-link                   v5.0.2             Symfony WebLink Component
symfony/web-profiler-bundle        v5.0.2             Symfony WebProfilerBundle
symfony/yaml                       v5.0.2             Symfony Yaml Component

```

**Comment by garak** [comment]
I finally made it working by requiring `nyholm/psr7`.
But I'm a bit confused, since the same project was working without it before updating vendors.

So, feel free to close this issue if it's not relevant (but, hey, if you can shed some light on what happened I'd really appreciate it)

**Comment by codedmonkey** [comment]
This is intended behavior as it checks for the availability of a PSR-17 factory for it to recognize the Symfony HTTP client, since Symfony doesn't include one by default.

I think it would be more developer-friendly to just recognize the Symfony client anyway, and give an error there were no supported PSR-17 factories available. I would be happy to create a PR if somebody from the HTTPlug team approves.

**Comment by dbu** [comment]
that is a dilemma (and one more reason why i am pessimistic about discovery in general) - there might be another client that is usable. if we fail in that case, we interrupt the discoveries.

if somebody installed symfony/symfony or just the symfony http client but not all necessary pieces that we need here, the http client is available but the factory is not... additionally, there might be guzzle or something else that can be used. so erroring will prevent the user from using that other option. we could think if its possible to log something somewhere when symfony/http-client is found but missing the factory? (not sure where the logs should go though, people won't go looking into the server logs i am afraid)

**Comment by codedmonkey** [comment]
The problem right now is that it isn’t documented at all. The best place would probably be the Symfony documentation itself, since it’s the one providing a client specific to HTTPlug.

**Comment by dbu** [comment]
mentioning it in the symfony documentation of their http client certainly is a good idea (if they accept the merge request). @codedmonkey do you want to do a pull request to add the note in the place where you would expect to have seen it?

and as the exception prints a link to http://docs.php-http.org/en/latest/discovery.html#common-errors i suggest that someone add a note about that under the http://docs.php-http.org/en/latest/discovery.html#could-not-find-resource-using-any-discovery-strategy heading that if you have symfony/http-client you also need nyholm/psr7 for it to work. @codedmonkey want to do that too?

@Nyholm what is your take on this? how can we make this easier to figure out? can we log this (symfony client exists but there is no psr7 impl available) somewhere somehow that it can be found? any other ideas where to put information? we could also add a check in the place that creates the exception message, because if symfony/http-client is present and no client found, this is the most likely solution people want to take...

**Comment by matt-allan** [comment]
I'm getting this error even though I have `nyholm/psr7` installed.

The error seems to indicate Discovery is trying to load `Symfony\Component\HttpClient\HttplugClient` instead of `Symfony\Component\HttpClient\Psr18Client`.

```
PHP Fatal error:  Uncaught LogicException: You cannot use "Symfony\Component\HttpClient\HttplugClient" as the "php-http/httplug" package is not installed. Try running "composer require php-http/httplug". in /Users/matt/code/discovery-repro/vendor/symfony/http-client/HttplugClient.php:44
Stack trace:
#0 /Users/matt/code/discovery-repro/vendor/composer/ClassLoader.php(444): include()
#1 /Users/matt/code/discovery-repro/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/Users/matt/cod...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('Symfony\\Compone...')
#3 [internal function]: spl_autoload_call('Symfony\\Compone...')
#4 /Users/matt/code/discovery-repro/vendor/php-http/discovery/src/Strategy/CommonClassesStrategy.php(115): is_subclass_of('Symfony\\Compone...', 'Psr\\Http\\Client...')
#5 [internal function]: Http\Discovery\Strategy\CommonClassesStrategy::getCandidates('Psr\\Http\\Client...')
#6 /Users/matt/code/discovery-repro/vendor/php-http/discovery/src/ClassDiscovery.php(56): call_user_ in /Users/matt/code/discovery-repro/vendor/symfony/http-client/HttplugClient.php on line 44
```

I pushed an example [here](https://github.com/matt-allan/php-http-discovery-issue-165).

**Comment by GrahamCampbell** [comment]
I think this can be closed. You need to require `nyholm/psr7` to use `symfony/http-client`?

**Comment by GrahamCampbell** [comment]
Symfony's docs kinda say this, but not very well.

**Comment by GrahamCampbell** [comment]
Symfony 4: `symfony/http-client:^4.4 nyholm/psr7:^1.3`
Symfony 5: `symfony/http-client:^5.0 nyholm/psr7:^1.3`

**Comment by GrahamCampbell** [comment]
I think we should add this to the install tests.
