### ISSUE TITLE
Broken php5.4 compatibility

### ISSUE THREAD

**Issue by eduard-sukharev** [php-http/discovery#186]
**PHP version**: 5.4.45

**Description**
In `Http\Discovery\MessageFactoryDiscovery::find()` on line 26 the `::class` constant is used, which became available only in PHP5.5. This breaks compatibility.

**How to reproduce**
Add
```
  "config": {
    "platform": {
      "php": "5.4.45"
    }
  },
```
to composer.json and install `httplug/guzzle5-adapter` and all required dependencies. Try running any sample code and get error.

**Possible Solution**
1. Fix compatibility by removing this (and possibly other) uses of `::class` and release new 0.9.x tag
2. Bump required php version in composer.json to 5.5

**Comment by dbu** [comment]
the current version is 1.10, list of versions can be found here: https://github.com/php-http/discovery/releases

it is unfortunate if a 0.9 version allowed php 5.4 but used the ::class constant, but i don't think we can fix this. if we tag a new 0.9.x version, composer on php 5.4 will just pick the old broken version. (i think [0.9.1](https://github.com/php-http/discovery/releases/tag/v0.9.1) already did that). the only solution would be to create a branch from 0.9.1 and replace ::class with class names, allow 5.4 again and tag it as 0.9.2. but i doubt that this is worth the effort (people stuck on antique php 5.4 are not that likely to switch their http implementation, i would expect. though as you report this, you probably just did...) - if you want to look into it, i can set up the 0.9 branch in this repository and review the pull request.

**Comment by Nyholm** [comment]
Thank you @dbu
