### ISSUE TITLE
Use the corresponding StreamFactory in MessageFactory

### ISSUE THREAD

**Issue by sagikazarmark** [php-http/discovery#19]
Currently code is duplicated in Message and Stream factories. Thanks to @mekras we now have Stream factories which we can use to create streams.

Few solutions in my mind:

1. Accept a StreamFactory in the MessageFactory constructor (downside: increases complexity, also, I don't want the Guzzle message factory to use the diactoros one)
2. Instantiate the corresponding StreamFactory in the Message factory. (downside: hard coupling)
3. Mixture of the two: accept setter injection but fallback to a default implementation.

**Comment by Nyholm** [comment]
I believe it is very rare that you want one implementation of the Streams and another for the Message factory. I would not mind option 2. 

But of course, option 3 is preferred. It will give a lot of flexibility and in most cases you don't have to think about it at all.

**Comment by sagikazarmark** [comment]
> It will give a lot of flexibility and in most cases you don't have to think about it at all. 

Sure, but I wonder if we really need this. I would also choose option two.

**Comment by mekras** [comment]
This stream related code is specific for Zend Diactoros and has no abstract dependencies. So it can be extracted into separate class (may be static method or even function). Both factories just can instantiate it (or call function).

**Comment by Nyholm** [comment]
If we do 2 now, we could easily implement 3 without breaking BC. (If the community see a need for it)

**Comment by mekras** [comment]
For example Guzzle use function `\GuzzleHttp\Psr7\stream_for` to create streams.

**Comment by sagikazarmark** [comment]
@Nyholm indeed, so lets go with option two for now. Thanks.

@mekras you are right as well. I am still thinking about if we should be consistent and just instantiate the StreamFactory in case of Guzzle as well, but it isn't a BC break to change it, so I will use the stream function in case of Guzzle.

Thanks guys.

**Comment by dbu** [comment]
+1 for option 2 for now
