### ISSUE TITLE
Deprecated findUrlFactory deprecation notice refers to self.

### ISSUE THREAD

**Issue by letharion** [php-http/discovery#193]
```
      /**
       * @return UriFactoryInterface
       *
       * @throws Exception\NotFoundException
       *
       * @deprecated This will be removed in 2.0. Consider using the findUrlFactory() method.
       */
      public static function findUrlFactory()
      {
          return static::findUriFactory();
      }
```

I'm looking at fixing this deprecation notice, but since the suggestion appears to be saying I should be using the deprecated function itself, I'm not sure what to make of this.

**Comment by dbu** [comment]
that was a typo in the deprecation notice which has been fixed in master but apparently not in the version you have installed: https://github.com/php-http/discovery/blob/master/src/Psr17FactoryDiscovery.php#L130

use the findUriFactory - that is consistent with it returning an UriFactoryInterface
