### ISSUE TITLE
Slack site down?

### ISSUE THREAD

**Issue by letharion** [php-http/discovery#194]
http://slack.httplug.io/ yields an error message, as opposed to a chat.

![bild](https://user-images.githubusercontent.com/494592/100584917-08ba5800-32ed-11eb-85fb-727f573565e4.png)

**Comment by dbu** [comment]
@sagikazarmark can you check this one please?

**Comment by sagikazarmark** [comment]
Yeah, looking at it. Looks like Slack killed the possibility to send invites using Slackin. :\

I'm looking for an alternative.

**Comment by sagikazarmark** [comment]
@letharion I can send you an invite directly if you wish.

**Comment by letharion** [comment]
@sagikazarmark Thanks, I don't need one at the moment

**Comment by sagikazarmark** [comment]
Apologies for taking the time on this one. It should now redirect to a non-expiring slack invite link.
