### ISSUE TITLE
Make factories final

### ISSUE THREAD

**Issue by sagikazarmark** [php-http/discovery#20]
Are there any cases where we want to extend them?

They are pretty simple, so I don't think reimplementing them is a problem.

**Comment by dbu** [comment]
given that they are accessed with static method calls, i think it makes
sense to make them final. no way to customize code behaviour
transparently anyways. the way to use a custom client is to use the
`register` method.

**Comment by sagikazarmark** [comment]
Talking about factories, not discovery classes. But discovery classes should probably be final as well.

**Comment by dbu** [comment]
ah. right, well discovery definitely can be final. lets make the factories final and see. making them non-final later is no BC break so we can adapt if a valid use case turns up. most of the time, it should be plugins doing things rather than factories cleaning up stuff.

**Comment by Nyholm** [comment]
+1 for making both discovery and factory classes final.

**Comment by sagikazarmark** [comment]
What about the NotFoundException?
