### ISSUE TITLE
Endless Loop in composer update call

### ISSUE THREAD

**Issue by brosenberger** [php-http/discovery#211]
**PHP version**:  7.4, 8.1

**Description**
Calling composer update in a magento2 project (v2.4.3-p1, v2.4.5-p1) with the enabled module leads to an endless lookup loop

**How to reproduce**

**Possible Solution**

**Additional context**
example trace:

ddev composer update
Loading composer repositories with package information
In Laminas\DependencyPlugin\DependencyRewriterV2::onPrePoolCreate
Updating dependencies
Nothing to modify in lock file
Installing dependencies from lock file (including require-dev)
Nothing to install, update or remove
Package fgrosse/phpasn1 is abandoned, you should avoid using it. No replacement was suggested.
Package symfony/debug is abandoned, you should avoid using it. Use symfony/error-handler instead.
Package php-cs-fixer/diff is abandoned, you should avoid using it. No replacement was suggested.
Generating autoload files
133 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
Loading composer repositories with package information
In Laminas\DependencyPlugin\DependencyRewriterV2::onPrePoolCreate
Updating dependencies
Nothing to modify in lock file
Installing dependencies from lock file (including require-dev)
Nothing to install, update or remove
Package fgrosse/phpasn1 is abandoned, you should avoid using it. No replacement was suggested.
Package symfony/debug is abandoned, you should avoid using it. Use symfony/error-handler instead.
Package php-cs-fixer/diff is abandoned, you should avoid using it. No replacement was suggested.
Generating autoload files
133 packages you are using are looking for funding.
Use the `composer fund` command to find out more!

**Comment by PabloKowalczyk** [comment]
Same here.

Possible, temporary, workaround is to modify `composer.json`:
```json
"conflict": {
    "php-http/discovery": "1.15.0"
},
```

**Comment by Cluster2a** [comment]
I just disabled the plugin:
```json
"allow-plugins": {
    "php-http/discovery": false
}
```

**Comment by brosenberger** [comment]
> I just disabled the plugin:
> 
> ```json
> "allow-plugins": {
>     "php-http/discovery": false
> }
> ```

that was my solution for now too

**Comment by pleaz** [comment]
if you use Docker container or need to enable it, that's working with previous version [1.14.3]

**Comment by claudiu-cristea** [comment]
Same here (PHP 8.1) when running `composer update -W`

**Comment by pl38** [comment]
Same php@8.1 cu -Wo

**Comment by steffenf14** [comment]
same with all of our projects. php7.3 7.4 and 8.0
