### ISSUE TITLE
Latest version tries to do update again but this time without composer flags that were given.

### ISSUE THREAD

**Issue by sakarikl** [php-http/discovery#215]
**PHP version**: x.y.z (hint: `php --version`)

8.1

Gathering patches for root package.
Loading composer repositories with package information
Updating dependencies                                                        
Dependency resolution completed in 0.003 seconds
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires PHP extension ext-apcu * but it is missing from your system. Install or enable PHP's apcu extension.
  Problem 2
    - Root composer.json requires PHP extension ext-imagick * but it is missing from your system. Install or enable PHP's imagick extension.
  Problem 3
    - Root composer.json requires PHP extension ext-oci8 * but it is missing from your system. Install or enable PHP's oci8 extension.
  Problem 4
    - Root composer.json requires PHP extension ext-stats * but it is missing from your system. Install or enable PHP's stats extension.
  Problem 5
    - Root composer.json requires PHP extension ext-ssh2 * but it is missing from your system. Install or enable PHP's ssh2 extension.

**Comment by Tofandel** [comment]
Fixed by #216
