### ISSUE TITLE
Reorder priorities of PSR-17 factories

### ISSUE THREAD

**Issue by boesing** [php-http/discovery#222]
**Description**

Hey there,
I recently ran into an issue regarding `urlencode` of `userInfo`. Due to whatever reasons, `nyholm/psr7` does not encode the password and thus, `curl` returns error code 3 (malformed URI) when executing a request with a password containing characters which need to be `urlencode`.

Since `nyholm/psr7` did not received any updates for quite a long time, I assume it is either not maintained or the pace of fixing [issues](https://github.com/Nyholm/psr7/issues) reduced. Since there are PSR-17 implementations of industry approved libraries, I am not quite sure why `nyholm/psr7` has almost the highest priority when detecting PSR-17 factories.

For example:
- `guzzle/psr7`
- `slim/psr7`
- `laminas/diactoros`

When it comes to PSR-18, symfony and guzzle have the highest priorities and there are no doubts. I'd expect `guzzle` to always overrule `nyholm/psr7` as well.

**Example**

```php
$uri = new \Nyholm\Psr7\Uri('http://example.org');
$uri = $uri->withUserInfo('username', 'password#');

echo (string) $uri; // http://username:password#@example.org => when used with curl, curl error 3 malformed uri

$uri = new \GuzzleHttp\Psr7\Uri('http://example.org');
$uri = $uri->withUserInfo('username', 'password#');

echo (string) $uri; // http://username:password%23@example.org => when used with curl, all good
```

**Additional context**

It also seems that @Nyholm is not interested in interoperability of his component.

> I just quickly checked PSR7 specification and it does not mention anything about URL encoding.

_https://github.com/Nyholm/psr7/pull/202#issuecomment-1216370651_

> I see no reason to change unless a PSR is updated with clear guidelines.

_https://github.com/Nyholm/psr7/issues/99#issuecomment-453041130_

When I understand this discovery component correct, it is expected that *every* discovered PSR-18/PSR-17 implementation does support the same functionality as if not - it won't be interchangeable.

Since in the mentioned comments above the response was "I dont care unless PSR cares" while the authors of the issues stated that other implementations actually do support these (so not just one), I frankly would prefer having `nyholm/psr7` either removed or the priority should be lowered so that other components are picked up first.

**Comment by nicolas-grekas** [comment]
nyholm/psr7 just happens to be stable. It *is* well maintained AFAIK. Did you submit an issue there? What about a fix?

**Comment by nicolas-grekas** [comment]
Looks like I missed following the links you submitted :grimacing:
Let's revive those.

**Comment by boesing** [comment]
Well, especially for the mentioned error above, a [PR](https://github.com/Nyholm/psr7/pull/202) does exist since August 2022.
But instead of going the way, as the other implementations, @Nyholm suggested to throw errors when "invalid" characters are passed. Due to the interoperability idea of this discovery component (correct me if I'm wrong, because if that is not the idea, I might not get it at all), I still expect most if not all discovered implementations behave the same.

Especially in my recent case, everything worked well due to the fact that the discovery seemed to detect guzzle PSR-7 implementation. Due to a transitive dependency, both  `php-http/discovery` and `nyholm/psr7` (first required by `elasticsearch`, second by another 3rd-party library we recently updated) are installed in our project and thus, we were not even aware that the discovery magic ever happened. However, since `nyholm/psr7` has the 2nd highest priority in this discovery, `elasticsearch` stopped working for us due to the production password contains `#`.

Only thing changed was `composer.json` and `composer.lock`. That was really surprising and I can't believe that this is how its meant to work.

----

I wonder if it would work to actually have a config file in the project to enforce this component to always detect the same implementations regardless of what is installed. I am aware of the fact that I can modify the discovery strategies at runtime but I'd prefer my code (besides a config file) to not interact with this component at all (as we do not directly depend on it but via transitive dependencies).

**Comment by nicolas-grekas** [comment]
I see several next steps:
- continue this discussion with nyholm/psr7
- make elasticsearch + that other dep use discovery instead of them hardcoding a dep
- I like your idea to pin a preference. It'd do it with an entry in composer.json, read by the composer plugin, which would then generate some file to configure the factory on bootstrap.

Would you like to help on these? I contacted @Nyholm to talk about item 1.

**Comment by boesing** [comment]
> continue this discussion with nyholm/psr7

I will, but it seems to be a one-way discussion since I somehow understand the standpoint of "if PSR does not say so, we do not implement it" but then the interoperability is not given 🤷🏼‍♂️ The suggested way forward with throwing `InvalidArgumentException` in `nyholm/psr7` is not what I'd expected.

> make elasticsearch + that other dep use discovery instead of them hardcoding a dep

Elasticsearch is already using the discovery component. Regarding that other dep, I am already on it. Its some company internal thingy and thus I have (limited) ways to pursue this problem. 👍🏼 

> Would you like to help on these?

Definitely. Not sure if a composer plugin is a good idea tho. Was more thinking of some kind of PHP file where a proper mapping could happen.

Something like:

_php-http-discovery.config.php_
```php
<?php
return [
    'static-mapping' => [
        \Psr\Http\Client\ClientInterface::class => \GuzzleHttp\Client::class,
        // PSR-17 below, [...]
    ],
];
```

This way, IDE, static-analysis, etc. can already show if stuff is available or not without having to run any runtime checks. When adding stuff to `composer.extra` for example, having class-names stored in JSON is usually not that painfree while it also needs proper CI setup with plugins allowed to run, etc.
The PHP file would also be opcachable and thus the amount of additional I/O won't be that much.

**Comment by nicolas-grekas** [comment]
This package is already a composer plugin so it would be super natural to use the extra entry in composer.json for this.

**Comment by boesing** [comment]
Ah, didn't realized that tbh. Seems that it was added with 1.15 but we are still on 1.14. Well, then it would be doable ofc.
So what would you expect the plugin to do? Not sure if I understand the goal.

So I can add in `composer.extra.http-discovery` a dependency?
For example:

```json
{
    "extra": {
        "http-discovery": {
            "psr/http-client-implementation": "guzzlehttp/guzzle",
            "psr/http-factory-implementation": "guzzlehttp/psr7",
            "...": "..."
        }
    }
}
```

So that it can be extracted by the plugin, which then can verify if the added implementation is part of the `PROVIDE_RULES` AND the package is installed in the required version (defined in `PROVIDE_RULES` as well as far as I can see).
But the main question is, where to put that information so that it will actually gets picked-up by the discovery classes.

I am thinking of a `PinnedByProjectStrategy` which is generated by the composer plugin and prepended to the factories.
Or do you have something else in mind?

**Comment by Nyholm** [comment]
I think there are multiple definitions of "interoperability" floating around. `nyholm/psr7` has always been about following the PSR and RFC specifications. It does not add any other features. 

I do agree with you that there is something missing here from PSR-7 and that sucks. 

I think the issue here is that you rely on features in Guzzle and expect them to be implemented everywhere. Instead you should rely on features in PSR-7. 

------

I understand your frustration, I understand it is not easy. `nyholm/psr7` is not opinionated, it is [strict](https://github.com/Nyholm/psr7#our-goal)

------

I do agree with you that we should not silently fail. We definitely need https://github.com/Nyholm/psr7/pull/202

**Comment by boesing** [comment]
What should not happen at all is that just because a composer depenency is being added or removed, the whole way of how stuff is interacting with PSR changes.

I do not rely on Guzzle features but on features which are supported by [guzzle](https://github.com/guzzle/psr7/blob/3cf1b6d4f0c820a2cf8bcaec39fc698f3443b5cf/src/Uri.php#L591), [laminas](https://github.com/laminas/laminas-diactoros/blob/b2355dc58253c480aa25ba085845a5aabf84955d/src/Uri.php#L551), [slim](https://github.com/slimphp/Slim-Psr7/blob/a6f0caef429144986bd3d1325f4924f7c3b75969/src/Uri.php#L195) and [phalcon](https://github.com/phalcon/phalcon/blob/edb5189750bb924211c752e63833d74fc5cce0ba/src/Http/Message/Uri.php#L813) (so literally by ALL other implementations supported by this discovery package). So you can ofc say "well, I still don't care" and thats absolutely okay, but then please move the priority of your package to the very end of the discoverable implementations.

**Comment by Nyholm** [comment]
I do understand what you mean. I do understand your frustration. I do think something should be changed. But you are still wrong =)

If you write code using an interface. The contract ("api") is with that interface. It does not matter what all/most implementations are doing. You can never trust the implementation. 

I agree that it is strange that the interface does not specify the super common feature you are asking for. 


Anyhow, it does not matter if you see it the same way that I do or not. We do need change as you suggest. 

@nicolas-grekas can you please make a decision what the best way forward is and take action?

**Comment by nicolas-grekas** [comment]
My reco is to go with https://github.com/Nyholm/psr7/pull/213

**Comment by dbu** [comment]
thanks for the constructive discussion, i appreciate it!

in terms of interoperability, indeed relying on the urlencoding seems to be the "mistake", as it is not specified in PSR-7. in an ideal world, PSR-7 would be more precise, or even come with a comprehensive test suite that guarantees consistent behaviour of all compliant implementations.

i like nicolas' suggestion to adjust nyholm/psr7 to work closer to the other implementations, and wonder if we can propose to upgrade psr-7 to be specific about this behaviour for future versions of psr7?

the auto-installation that @nicolas-grekas contributed to this discovery package already chooses the matching psr7 package, e.g. in a project with laminias the laminas packages or with guzzle the guzzle psr 7.

i wonder if we should instead of a strict order of preference say that if one of the major psr18 client is available, we use the psr7 implementation of that client. in theory, all psr7 implementations should work with all psr18 clients, but in practice the operation of laminas with its psr7 or guzzle with its psr7 are the cases that are the most well tested. wdyt?

**Comment by dbu** [comment]
i created https://github.com/php-fig/fig-standards/pull/1298, lets see

**Comment by nicolas-grekas** [comment]
I'm closing here because I think we resolved the topic. I opened #223 to keep track of the idea of pinning.
