### ISSUE TITLE
Allow pinning an implementation when several are available

### ISSUE THREAD

**Issue by nicolas-grekas** [php-http/discovery#223]
When `vendor/` contains several implementations of e.g. PSR-17, the discovery classes will select one based on some internal order of preference.

But the author of an app should be able to decide which implementation should be preferred.

There are already static methods to configure this, but it'd be great to allow specifying this in composer.json files.

To make this really fast, reading this value should be handled at "composer install" time, when the plugin can generate an ad hoc config file in PHP.

**Comment by boesing** [comment]
I had a quick look into this.
No clue what is going on within the provided composer plugin in here.
I've already written some composer plugins but this one here is that kind of complex that I won't dare touching it.

I would still prefer some kind of `php-http-discovery.config.php` within the project root.
Can be simply detected, can provide strategy-compliant `class-string` + `callable` (which won't work for the composer method) and the file will be opcached.
No struggle with upstream projects have weird CI pipeline which passes `--no-plugins`, etc. and super simple to implement.

Please let me know if you want to stick with composer plugin magic or if I can provide a patch reading `php-http-discovery.config.php` from project root. If it will be the plugin, I see me unable to provide a suitable patch and will see if I find another solution.

**Comment by nicolas-grekas** [comment]
See implementation in #232
