### ISSUE TITLE
Class "Nyholm\Psr7\Factory\HttplugFactory" is deprecated

### ISSUE THREAD

**Issue by zerkms** [php-http/discovery#246]
**PHP version**: x.y.z (hint: `php --version`)   8.1.19

**Description**

`nyholm/psr17` has deprecated Nyholm\Psr7\Factory\HttplugFactory in 1.8.0: https://github.com/Nyholm/psr7/blob/master/CHANGELOG.md#180

It's now suggested to use `Nyholm\Psr7\Factory\Psr17Factory` instead

**How to reproduce**

**Possible Solution**

**Additional context**

**Comment by BadJacky** [comment]
You can get details on https://github.com/php-http/discovery/pull/251

**Comment by dbu** [comment]
the httplugfactory implements the factories from the also deprecated https://github.com/php-http/message-factory

indeed one should use psr17 factories instead.

the discovery is still able to discover the legacy code to avoid a BC break.
