### ISSUE TITLE
Symfony 7 no longer implements Http\Client\HttpClient

### ISSUE THREAD

**Issue by arokettu** [php-http/discovery#252]
**Description**
symfony/http-client no longer implements Http\Client\HttpClient so discovery should not return it.

**How to reproduce**
run 
```php
<?php
var_dump(\Http\Discovery\HttpClientDiscovery::find() instanceof  Http\Client\HttpClient); // false
```
with symfony/http-client v7 installed

**Comment by dbu** [comment]
oh, you are right. can you do a pull request to change the discovery to skip the rules for the symfony client if their client does not implement the interface? (as the http-client can be installed stand alone, we can't check the kernel for symfony version, but an instanceof check seems good to me)

note that the php-http interface has been deprecated in favor of `Psr\Http\Client\ClientInterface`

**Comment by arokettu** [comment]
Something like that? #253
