### ISSUE TITLE
Extract factories

### ISSUE THREAD

**Issue by sagikazarmark** [php-http/discovery#26]
Unfortunately guzzle/psr7#50 hasn't been accepted which made me think about the current state of factories and discovery.

Currently we have all our Factory implementations in the discovery repo, which makes the actual implementations nearly unusable in cases where the discovery layer is not needed.

IIRC @mekras suggested a while ago to separate the factories from the discovery layer. Although we refused to do (I don't remember the reasons, probably to many packages and dependencies?) we should reconsider this. I see three possible ways:

1. Leave it as is.
2. Separate factories to implementation specific packages and

    A. require the implementation itself as well
    B. only suggest the implementation

In case of "A" we cannot really use the factories automatically anymore in the discovery layer, but we have to install them manually, based on the chosen implementation.

In case of "B" we can require all the factory packages in the discovery layer, so we could use it as usual. Although in this case we also install lots of extra dependencies.

**Comment by dbu** [comment]
the message factories interfaces are defined in message-factories. but
the implementation lives here together with discovery.
for Httplug, the interface is defined in httplug, the implementation
live in adapter.

complicated. what if we move message factories that we know of into the
message-factories repository? that would make more sense to me.

separating the factory implementations into their own repo, but then
require them from discovery seems complicated. yeah, if i don't want
discovery i can require them separately.

i think my order of preference is:

1. move factory implementations into same repo as interfaces
2. move them to a separate repository and require them
3. move them to separate repository per implementation (guzzle,
diactoros) and require all of them
4. leave as is

**Comment by sagikazarmark** [comment]
Maybe we could move the factory implementations to utils. It is for library implementors anyway.

Also, we don't even have to require it in the discovery package. We just need to check for the Factory and the Message existence. In this case the discovery package can purely be a discovery layer. We can place a warning, that to use our factories, the utils package should also be installed.

**Comment by dbu** [comment]
i like this idea. lets do that!
