### ISSUE TITLE
Class "Nyholm\Psr7\Factory\HttplugFactory" is deprecated since version 1.8, use "Nyholm\Psr7\Factory\Psr17Factory" instead

### ISSUE THREAD

**Issue by Axent96** [php-http/discovery#260]
**PHP version**: x.y.z (hint: `php --version`)
8.2.7
**Description**

Class "Nyholm\Psr7\Factory\HttplugFactory" is deprecated since version 1.8, use "Nyholm\Psr7\Factory\Psr17Factory" instead

**How to reproduce**

in CommonClassesStrategy.php

**Possible Solution**

replace with Nyholm\Psr7\Factory\Psr17Factory
**Additional context**

**Comment by dbu** [comment]
please use Psr17FactoryDiscovery instead of the [also deprecated](https://github.com/php-http/discovery/blob/1.x/src/MessageFactoryDiscovery.php#L13) MessageFactoryDiscovery
