### ISSUE TITLE
Auto/Lazy discovery

### ISSUE THREAD

**Issue by sagikazarmark** [php-http/discovery#29]
Currently discovery classes are used in case a resource (Client, MessageFactory, etc) is not passed. Used as a fallback if you like. However these fallbacks are usually resolved in a constructor which makes them immediately instantiated, which does not make much sense, if you can also set the resource using a setter.

To mitigate this problem, I propose to implement Auto/Lazy discover, which would work like the following: instead of using the `find` method of discoveries, a new Autodiscovery object is instantiated (specific to the resource type).

When you actually want to use this resource the first time, the autodiscovery gets initialized and invokes the underlying find method.

PS: I realized after writting the description that I actually described Proxies. So lets call them Proxies instead.

**Comment by dbu** [comment]
using a setter for this dependency sounds like bad design.

if an implementor is concerned with this, they could also use a
`getClient`, `getMessageFactory` and so on method that uses late
discovery if none was explicitly set.

i am -1 on putting effort into this, its only adding extra convenience
to a bad design.

(note: if we end up doing it, we should probably use
ocramius/proxy-manager for it - thats a really cool library for proxies)

**Comment by sagikazarmark** [comment]
Yeah, :+1: proxy manager. Let's keep this open for a while, but it is really not a top priority.

**Comment by sagikazarmark** [comment]
Closing this as we are clearly moving towards the DI/Discovery direction.
