### ISSUE TITLE
Guesser for UriFactory

### ISSUE THREAD

**Issue by ddeboer** [php-http/discovery#3]
And probably UriFactory implementations for Guzzle and Diactoros?

**Comment by sagikazarmark** [comment]
Where would it be necessary? By definition message factories accept string or UriInterface, so URIs are converted to an UriInterface by the message factory which means that you will never need to create an UriInterface object directly.

What use case can you imagine? Or is it for the sake of completeness? If so, StreamFactory implementations as well? (The message factory contract package has an interface for Messages, Uris, Streams as well)

**Comment by ddeboer** [comment]
Use case: an object that needs to perform HTTP requests (using php-http/adapter) and that you can set a base URI on (that will be used for any of the requests from that object). Instead of parsing and validating that URI on your own it makes sense to use any of the PSR-7 libraries that must be available anyway to create the request objects.

**Comment by sagikazarmark** [comment]
Valid point.

Would you like to provide a PR or let me do the hard copy-pasting? :wink:

**Comment by ddeboer** [comment]
I was already copy-pasting it, so I’ll submit it in a minute.

**Comment by sagikazarmark** [comment]
Cool :+1:
