### ISSUE TITLE
Better exception message when class not found

### ISSUE THREAD

**Issue by Nyholm** [php-http/discovery#35]
When we do not find a factory we [throw an exception](https://github.com/php-http/discovery/blob/master/src/FactoryDiscovery.php#L21) like this: 
```php
"No factories found. Install php-http/message to use Guzzle or Diactoros factories."
```
This is not correct. You could have `php-http/message` installed and still get this error. We should explain better that you need `php-http/message` and an implementation of PSR-7. 

Same with the `HttpAsyncClientDiscovery` and `HttpClientDiscovery`, atm we get an exception saying "Not found". This could also be improved.

**Comment by sagikazarmark** [comment]
You are right, the message is incorrect.

As for the other discoveries: We could extend the message to say that the given resource type has no available implementation.

**Comment by Nyholm** [comment]
:+1:
