### ISSUE TITLE
Documentation for 0.6.0

### ISSUE THREAD

**Issue by ddeboer** [php-http/discovery#36]
The introduction of Puli requires people to have Puli’s CLI installed for discovery to work (when running `composer install/update`). Is that correct, @sagikazarmark?

**Comment by sagikazarmark** [comment]
Yes. I was thinking about directly adding puli/cli dependency to discovery, but that's an environmental detail: either install it where you actually use puli or install the cli phar globally (I guess the latter is better)

**Comment by sagikazarmark** [comment]
Documentation for discovery must be rewritten anyway.

**Comment by ddeboer** [comment]
If we add it as a dependency in `composer.json`, will it still be installed if it has already been installed globally?

**Comment by sagikazarmark** [comment]
Yes. By globally I only meant the puli.phar, but you can of course install the li package itself globally.

**Comment by ddeboer** [comment]
Just saw https://github.com/php-http/documentation/issues/48, so continuing discussion there.
