### ISSUE TITLE
Puli Factory is not available

### ISSUE THREAD

**Issue by nWidart** [php-http/discovery#38]
Hello,

I'm using the `Happyr/LinkedIn-API-client` package, which has recently been updated to use PSR-7.

Since the update I'm getting the following error:
```
[RuntimeException]             
Puli Factory is not available
```

This happens in the `ClassDiscovery` class on `getPuliFactory` method.

When going to https://github.com/puli/factory, I see it's not maintained anymore.

Anything I missed ?

**Comment by sagikazarmark** [comment]
For the time being you need to install puli/cli. Either the PHAR in your prefix or the package in your application. This should change soon and discovery will require puli/cli.

**Comment by sagikazarmark** [comment]
See php-http/discovery#39

**Comment by dbu** [comment]
this is fixed if you require `php-http/discovery: "^0.6.2"`

**Comment by nWidart** [comment]
Thank you for the quick answer.
I've required version 0.6.2. 

However I'm now getting this error:

```
[Http\Discovery\NotFoundException]                                                                                        
  No factories found. To use Guzzle or Diactoros factories install php-http/message and the chosen message implementation.  

 [Http\Discovery\NotFoundException]                        
  Resource of type "Http\Message\MessageFactory" not found
```
From the message I assume I have to install `php-http/message`, but not sure what is ment by the implementation. Which one are there, which one should I pick?

Thank you,

**Comment by sagikazarmark** [comment]
Try installing 0.6.2 discovery (version override should work with the linkedin client. @Nyholm could update the required discovery version)

**Comment by sagikazarmark** [comment]
You have to install php-http/message to use Guzzle or Diactoros factories and the chosen message implementation package.

**Comment by dbu** [comment]
if i am not mistaken, requiring one of the adapters in your project is enough. `composer require php-http/guzzle6-adapter` should pull in php-http/message and everything else you need. at least this is what the tutorial at http://docs.httplug.io/en/latest/httplug/tutorial.html claims.

**Comment by nWidart** [comment]
Oh ok strange, I already had the `guzzle6-adapter`(version `0.3.1`), but `php-http/message` was missing. Requiring `php-http/message`, seems to be working now.

**Comment by sagikazarmark** [comment]
I think message should not be a dependency of guzzle6 adapter. The library doesn't need it internally. If you want to use message factories in your application, you need to install the dependencies. Discovery can be a dependency, where the client needs to discover a message factory, but implementations should still be installed manually.

**Comment by dbu** [comment]
okay. i think we still need to work on the documentation to make it easily understandable what you need to require in which situation. and @Nyholm will need to update his documentation or add something to the changelog, if its not already there.

@sagikazarmark if discovery is mainly for zero-config clients, would it make sense to have it require message? or should a library that uses the message factories do that itself? the later probably makes most sense. http://docs.httplug.io/en/latest/httplug/library-developers.html#messages should elaborate a bit more

**Comment by sagikazarmark** [comment]
By default, message provides some message factories. In a DI context you need to configure them and inject to the class using it. Discovery provides a zero-config way to find any installed message factories.

Also, discovery is most likely used by your library, while the implementation should be installed in the application.

Yes, we need better documentation for that.

**Comment by d4rkd0s** [comment]
Per the docs... I ran this command and produced the following error.
`php composer.phar require happyr/linkedin-api-client:dev-master php-http/httplug:v1.0.0-beta`

```
Running composer as root/super user is highly discouraged as packages, plugins and scripts cannot always be trusted
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for php-http/httplug v1.0.0-beta -> satisfiable by php-http/httplug[v1.0.0-beta].
    - Conclusion: remove php-http/promise v1.0.0
    - php-http/httplug v1.0.0-beta requires php-http/promise ^0.1 -> satisfiable by php-http/promise[v0.1.0, v0.1.1].
    - Can only install one of: php-http/promise[v1.0.0, v0.1.0].
    - Can only install one of: php-http/promise[v1.0.0, v0.1.1].
    - Installation request for php-http/promise (installed at v1.0.0) -> satisfiable by php-http/promise[v1.0.0].


Installation failed, deleting ./composer.json.
```

**Comment by sagikazarmark** [comment]
How is your problem related to this issue?

Per what docs?

HTTPlug is already stable, the referred package requires it, so I wonder where you found such an installation command.

**Comment by d4rkd0s** [comment]
@sagikazarmark this was a while back, it looks like things are fixed now. My fault for not posting the link to the docs :confounded: it was somewhere in here: http://docs.php-http.org/en/latest/index.html you can disregard my previous comment. I'm no longer using this lib.

**Comment by Nek-** [comment]
Same is happening to me... But not on composer something but on `bin/console` with a legacy Sf app that I'm upgrading... Still investigating.
