### ISSUE TITLE
Package not installable

### ISSUE THREAD

**Issue by egeloen** [php-http/discovery#46]
I just update my vendor and the puli build command becomes broken. I have try to remove my local puli.json and ./puli directory but still got the same error.

Here the stacktrace of the puli build command:

```
./bin/puli build -vv


                                              
  [InvalidArgumentException]                  
  The flags must be an integer. Got: boolean  
                                              


Exception trace:
  ()
    vendor/webmozart/assert/src/Assert.php:149
  Webmozart\Assert\Assert::integer()
    vendor/webmozart/key-value-store/src/JsonFileStore.php:119
  Webmozart\KeyValueStore\JsonFileStore->__construct()
    .puli/GeneratedPuliFactory.php:41
  Puli\GeneratedPuliFactory->createRepository()
    vendor/puli/manager/src/Api/Puli.php:508
  Puli\Manager\Api\Puli->getRepository()
    vendor/puli/manager/src/Api/Puli.php:653
  Puli\Manager\Api\Puli->getRepositoryManager()
    vendor/puli/cli/src/PuliApplicationConfig.php:208
  Puli\Cli\PuliApplicationConfig->Puli\Cli\{closure}()
    n/a:n/a
  call_user_func()
    vendor/webmozart/console/src/Api/Config/Config.php:285
  Webmozart\Console\Api\Config\Config->getHandler()
    vendor/webmozart/console/src/Api/Command/Command.php:499
  Webmozart\Console\Api\Command\Command->doHandle()
    vendor/webmozart/console/src/Api/Command/Command.php:388
  Webmozart\Console\Api\Command\Command->handle()
    vendor/webmozart/console/src/ConsoleApplication.php:266
  Webmozart\Console\ConsoleApplication->run()
    vendor/puli/cli/bin/puli:23
```

**Comment by egeloen** [comment]
Hum, I was able to fix it by downgrading `webmozart/key-value-store` from `1.0.0-beta7` to `1.0.0-beta6`.

**Comment by egeloen** [comment]
@sagikazarmark Is there a BC break in puli which breaks this package?

**Comment by sagikazarmark** [comment]
Probably. There are quite a few reports that the new beta breaks some stuff, but I haven't been able to find out the reason.

**Comment by egeloen** [comment]
Thanks for the feedback, I let it open since the root cause is fixed. Anyway as already pointed at, just need to downgrade the `webmozart/key-value-store` package and everything works again :)

**Comment by sagikazarmark** [comment]
The key-value store expects an integer, while a boolean value is passed in the generated factory.

**Comment by egeloen** [comment]
Should I open an issue on puli? Or is it something which need to be fixed in this package?

**Comment by sagikazarmark** [comment]
I am already wording the issue.

**Comment by egeloen** [comment]
:+1:

**Comment by sagikazarmark** [comment]
Try updating to 0.7 and removing .puli directory prior to composer up.

**Comment by egeloen** [comment]
Thanks will give a try more latter today. One question remains to me about puli, in a project should I add `puli.json` and `./puli` to the VCS or not?

**Comment by sagikazarmark** [comment]
I think `.puli/` should always be ignored. I think it is rather build artifact.

`puli.json` should be version controlled if you have any puli configuration/binding/etc. For example in adapters we commit puli json because of the binding, in httplug because of the binding type. But in HttplugBundle it is not necessary I think. If you don't have any config in a PROJECT you CAN ignore it as itt will always be generated, but I think it should be version controlled, as composer.lock.

**Comment by egeloen** [comment]
Thanks for the explanation! I confirm the 0.7 is working as expected.
