### ISSUE TITLE
Remove name argument from Discovery classes

### ISSUE THREAD

**Issue by sagikazarmark** [php-http/discovery#5]
As discussed in #4 

Reason against it: it allows to identify a class resource and allows to override it when registering one.

/cc @ddeboer

**Comment by ddeboer** [comment]
I prefer to remove the names and use priorities to make overriding lookups possible. Perhaps manually `register()`ed classes should *always* go before the default ones? That’s probably sufficient.

**Comment by sagikazarmark** [comment]
Priority only make sense when you register your custom adapters. I guess you won't install more than one adapters. Even if you would, you shouldn't care about which exactly is instantiated.

If this is true, we should just unshift the manually registered classes => done.

**Comment by ddeboer** [comment]
True, just put manually registered classes on top (so unshift).
