### ISSUE TITLE
Uncaught Error: Class 'Puli\GeneratedPuliFactory' not found 

### ISSUE THREAD

**Issue by Michael-Hamburger** [php-http/discovery#56]
Hello :)

I am trying to use AcceptOn (https://github.com/accepton/accepton-php) which is  using php-http.

I use:

- Windows 10 x64
- Xampp with php 7
- Composer

After some hassle I can instantiate the Client from AcceptOn. But when using the functionality I get **Fatal error: Uncaught Error: Class 'Puli\GeneratedPuliFactory' not found** in D:\Development\Repository\order\vendor\php-http\discovery\src\ClassDiscovery.php on line 37. The GeneratedPuliFactory.php is inside the .puli directory which is in the project root (order). The puli.phar is also located in the root directory and can be called via php puli.phar.

I also checked http://docs.php-http.org/en/latest/discovery.html#common-errors and run composer require puli/composer-plugin. Sadly the problem still exists.

Any Idea how I can solve this?
Thanks!

**Comment by sagikazarmark** [comment]
Are you trying to use it with Composer 1.0 and > 5.6 PHP?

**Comment by Michael-Hamburger** [comment]
On Windows I have:
Composer version 1.1.1 2016-05-17 12:25:44
PHP Version 7.0.1

I am currently testing the same thing on my raspberry pi 2 with composer 1.1.1 and php 5.6.20

**Comment by sagikazarmark** [comment]
Unfortunately this is known issue of puli which I reported here: https://github.com/puli/issues/issues/190

You will find a temporary solution in the issue as well. There is already a PR to fix the issue: https://github.com/puli/composer-plugin/pull/46

We are waiting for that and a new release.

**Comment by Michael-Hamburger** [comment]
Thanks. I can't use the quickfix because Undefined variable: loader. Looks like I need to paste the lines somewhere else? I tried the autoload.php

**Comment by sagikazarmark** [comment]
The loader variable should be your autoloader. This snippet is pasted to this file in my projects:

https://github.com/webplates/symfony-standard/blob/master/app/autoload.php

**Comment by sagikazarmark** [comment]
The best thing to do if you don't use symfony is to create your own bootstrap.php or autoload.php, require the composer autoloader there and apply this fix.

**Comment by Michael-Hamburger** [comment]
I added the snippet in the autoload_static.php under vendor/composer. That works for now. Now I can finally work on what I wanted to work somet time ago. Thanks! I will try your proposal later.

**Comment by sagikazarmark** [comment]
Okay, but keep in mind that composer regenerates autoload files, your change might be lost.

Please close the issue, if it is resolved.

Thanks

**Comment by JLepeltier** [comment]
on your composer file you can do :  
 "autoload": {      
        "classmap": [".puli/"]
    },
