### ISSUE TITLE
Ready for stable release

### ISSUE THREAD

**Issue by Nyholm** [php-http/discovery#62]
I started this issue from the discussion here: https://github.com/php-http/HttplugBundle/pull/81

Our BC promise in this library is the following functions:
```php
HttpAsyncClientDiscovery::find();
HttpClientDiscovery::find();
MessageFactoryDiscovery::find();
StreamFactoryDiscovery::find();
UriFactoryDiscovery::find();

ClassDiscovery::setStrategies();
ClassDiscovery::clearCache();

// And the
DiscoveryStrategy interface

// And our exceptions and when they are thrown
```

This API has nothing to do with the discovery methods (strategies) itself. The strategy classes should not be a part of our API promise. Which is a great thing. 

If we change the namespace of our clients we just add another "NewNamespacesStrategy" together with our existing `CommonClassesStrategy`.  Same with if Puli changes their API when they release 1.0. We just add a "Puli1Strategy". 

So if we leave the strategies outside our BC promise, are we ready for a stable release? At least, can we mature in to this API and tag 1.0 after the summer?

**Comment by joelwurtz** [comment]
Was also thinking the same, as we have now a stable api for discovery it is good for a stable release, maybe we can rename Puli strategy to PuliBetaStrategy in the meantime ? (So we can create a PuliStrategy when it is stable)

**Comment by dbu** [comment]
+1 for PuliBetaStrategy to make clear this is beta. once its stable, i
would hope that one strategy might work for all puli 1 versions, maybe
even puli 2...

**Comment by sagikazarmark** [comment]
I would add one more thing here: NotFoundException. The API became quite stable in 0.8 and many libraries (like mailgun) started to use it. I would really hate if they haven't updated because of the BC break between 0.8 and 0.9 (NotFoundException relocated). So I would add that exception back, extend the new exception and throw it temporarily (also deprecate it).

**Comment by dbu** [comment]
@sagikazarmark as long as we remove it for 1.0 i am +1 on that.

**Comment by sagikazarmark** [comment]
I think we should remove it in 2.0 to make transition from 0.8 to 1.0 easier. Otherwise it's a BC break for consumer libraries.

**Comment by dbu** [comment]
i would say caring a bit about BC for the 0.* versions to make upgrades
easier is fine, but 1.0 could be a cleanup. its not like this would be a
huge, hard to refactor problem. but if you insist, i can live with it.

**Comment by sagikazarmark** [comment]
I don't insist, but my concern is that libraries would stick to 0.8 to preserve THEIR BC. And it would be a problem, because they would stuck on older Bundle versions, older adapters, etc.

**Comment by dbu** [comment]
okay, you convinced me ;-)

**Comment by sagikazarmark** [comment]
If I am right, we did all the changes we wanted. So I think we could bring this to stable this week? Anything to add here?

**Comment by Nyholm** [comment]
Yes, I would like to figure out this first: https://github.com/php-http/HttplugBundle/pull/85

I hope I do not need any change in this repo, But lets wait an extra few days. I'll try to give some time to HttplugBundle the next coming days

**Comment by Nyholm** [comment]
I believe we are ready for tagging a stable 1.0.

**Comment by sagikazarmark** [comment]
I will do a final review and tag during the weekend.

**Comment by dbu** [comment]
i merged #76 so we should now be ready.

**Comment by sagikazarmark** [comment]
Cool, I will tag the stable soon.

**Comment by sagikazarmark** [comment]
Closed in https://github.com/php-http/discovery/tree/v1.0.0
