### ISSUE TITLE
Be compatible with php 5.4

### ISSUE THREAD

**Issue by kpn13** [php-http/discovery#99]
| Q            | A
| ------------ | ---
| Bug?         | no
| New Feature? | no

Hi,

If I'm right, this lib is not compatible with PHP 5.4 just because of "::class" used in tests. Are you against a PR which will replace "::class" by the fully qualified class name ?

Best regards.

**Comment by kpn13** [comment]
Sorry I just saw https://github.com/php-http/discovery/pull/61 so I imagine be compatible with 5.4 is not an option anymore.

**Comment by Nyholm** [comment]
Thank you for this PR. I see no reason to do work to support legacy versions of PHP. 

As soon as there is a PR with a decent reason to drop PHP 5.6 I would be happy to merge it =)
